const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||4173, ROOT=__dirname, DB_FILE=path.join(ROOT,'data.json');
const accounts={
 'admin@pizzachickenhut.pk':{password:'admin123',name:'Ahmed Khan',role:'Admin',initials:'AK'},'admin@pizzahut.pk':{password:'admin123',name:'Ahmed Khan',role:'Admin',initials:'AK'},
 'manager@pizzachickenhut.pk':{password:'manager123',name:'Saad Iqbal',role:'Manager',initials:'SI'},'manager@pizzahut.pk':{password:'manager123',name:'Saad Iqbal',role:'Manager',initials:'SI'},
 'cashier@pizzahut.pk':{password:'cashier123',name:'Hina Noor',role:'Cashier',initials:'HN'},'kitchen@pizzahut.pk':{password:'kitchen123',name:'Usman Raza',role:'Kitchen staff',initials:'UR'}
};
const seed={orders:[{id:'1048',customer:'Hassan Ali',channel:'Delivery',total:1750,status:'Preparing'},{id:'1047',customer:'Maryam K.',channel:'Pickup',total:2380,status:'Ready'},{id:'1046',customer:'Bilal Ahmed',channel:'Delivery',total:1080,status:'New'},{id:'1045',customer:'Fatima Noor',channel:'Pickup',total:650,status:'Completed'}],products:[{id:'p1',name:'Family Feast',category:'Deals',price:1750,available:true},{id:'p2',name:'Zinger Party',category:'Deals',price:1750,available:true},{id:'p3',name:'Medium Pizza',category:'Pizza',price:1080,available:true}],inventory:[{id:'i1',name:'Chicken fillet',quantity:4.5,unit:'kg',minimum:10},{id:'i2',name:'Mozzarella cheese',quantity:6,unit:'kg',minimum:12},{id:'i3',name:'Pizza flour',quantity:18,unit:'kg',minimum:10}],customers:[{id:'c1',name:'Hassan Ali',phone:'03xx-8047809',orders:18},{id:'c2',name:'Maryam Khan',phone:'03xx-413127',orders:12}],activity:[]};
let db=fs.existsSync(DB_FILE)?JSON.parse(fs.readFileSync(DB_FILE,'utf8')):seed;const sessions=new Map();
function save(){fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(data))}function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}function auth(req,res){const token=(req.headers.authorization||'').replace('Bearer ','');const user=sessions.get(token);if(!user){send(res,401,{error:'Authentication required'});return null}return user}
async function api(req,res,url){if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(req.method==='POST'&&url==='/api/auth/login'){const input=await body(req),email=(input.email||'').toLowerCase().trim(),account=accounts[email];if(!account||account.password!==input.password)return send(res,401,{error:'Invalid email or password'});const token=crypto.randomBytes(24).toString('hex'),user={email,name:account.name,role:account.role,initials:account.initials};sessions.set(token,user);return send(res,200,{token,user})}if(req.method==='POST'&&url==='/api/auth/logout'){const token=(req.headers.authorization||'').replace('Bearer ','');sessions.delete(token);return send(res,200,{ok:true})}if(req.method==='GET'&&url==='/api/auth/me'){const user=auth(req,res);if(user)return send(res,200,{user})}if(url==='/api/health')return send(res,200,{ok:true,service:'Pizza Chicken Hut API',time:new Date().toISOString()});const user=auth(req,res);if(!user)return;if(req.method==='GET'){if(url==='/api/dashboard')return send(res,200,{revenue:48650,orders:86,averageOrder:566,lowStock:5,role:user.role});for(const resource of ['orders','products','inventory','customers','activity'])if(url===`/api/${resource}`)return send(res,200,db[resource]);}if(req.method==='POST'){const match=url.match(/^\/api\/(orders|products|inventory|customers)$/);if(match){const resource=match[1],input=await body(req),item={id:crypto.randomUUID(),...input,createdAt:new Date().toISOString()};db[resource].push(item);db.activity.unshift({id:crypto.randomUUID(),user:user.name,action:`Created ${resource.slice(0,-1)}`,at:item.createdAt});save();return send(res,201,item)}}const patch=url.match(/^\/api\/orders\/([^/]+)$/);if(req.method==='PATCH'&&patch){const order=db.orders.find(x=>x.id===patch[1]);if(!order)return send(res,404,{error:'Order not found'});Object.assign(order,await body(req));db.activity.unshift({id:crypto.randomUUID(),user:user.name,action:`Updated order #${order.id}`,at:new Date().toISOString()});save();return send(res,200,order)}send(res,404,{error:'Route not found'})}
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg'};const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`).pathname;if(url.startsWith('/api/'))return await api(req,res,url);let file=url==='/'?'/index.html':url;const full=path.join(ROOT,file);if(!full.startsWith(ROOT)||!fs.existsSync(full))return send(res,404,{error:'Not found'});res.writeHead(200,{'Content-Type':mime[path.extname(full)]||'application/octet-stream'});fs.createReadStream(full).pipe(res)}catch(e){console.error(e);send(res,500,{error:'Server error'})}});server.listen(PORT,'0.0.0.0',()=>console.log(`Pizza Chicken Hut API running on 0.0.0.0:${PORT}`));
